//UPCOMING MOVIES
export const FETCH_UP_COMING_MOVIES_STARTED = 'FETCH_UP_COMING_MOVIES_STARTED';
export const FETCH_UP_COMING_MOVIES_SUCCESS = 'FETCH_UP_COMING_MOVIES_SUCCESS';
export const FETCH_UP_COMING_MOVIES_FAILED = 'FETCH_UP_COMING_MOVIES_FAILED';
export const FETCH_UP_COMING_MOVIES_REFRESH = 'FETCH_UP_COMING_MOVIES_REFRESH';
export const FETCH_UP_COMING_MOVIES_PAGINATE = 'FETCH_UP_COMING_MOVIES_PAGINATE';


//POPULAR MOVIES
export const FETCH_POPULAR_MOVIES_STARTED = 'FETCH_POPULAR_MOVIES_STARTED';
export const FETCH_POPULAR_MOVIES_SUCCESS = 'FETCH_POPULAR_MOVIES_SUCCESS';
export const FETCH_POPULAR_MOVIES_FAILED = 'FETCH_POPULAR_MOVIES_FAILED';
export const FETCH_POPULAR_MOVIES_REFRESH = 'FETCH_POPULAR_MOVIES_REFRESH';
export const FETCH_POPULAR_MOVIES_PAGINATE = 'FETCH_POPULAR_MOVIES_PAGINATE';


//TopRATED MOVIES
export const FETCH_TOP_RATED_MOVIES_STARTED = 'FETCH_TOP_RATED_MOVIES_STARTED';
export const FETCH_TOP_RATED_MOVIES_SUCCESS = 'FETCH_TOP_RATED_MOVIES_SUCCESS';
export const FETCH_TOP_RATED_MOVIES_FAILED = 'FETCH_TOP_RATED_MOVIES_FAILED';
export const FETCH_TOP_RATED_MOVIES_REFRESH = 'FETCH_TOP_RATED_MOVIES_REFRESH';
export const FETCH_TOP_RATED_MOVIES_PAGINATE = 'FETCH_TOP_RATED_MOVIES_PAGINATE';

//GET BY ID
export const GET_MOVIE_BY_ID_SUCCESS = 'GET_MOVIE_BY_ID_SUCCESS'
export const GET_MOVIE_BY_ID_FAIL = 'GET_MOVIE_BY_ID_FAIL'
export const CHANGE_DETAILS_PROPS = 'CHANGE_DETAILS_PROPS'

//Genes
export const GET_GENRES_LIST = 'GET_GENRES_LIST'

//Credits
export const GET_MOVIE_CREDITS_BY_ID_SUCCESS = 'GET_MOVIE_CREDITS_BY_ID_SUCCESS'
export const GET_MOVIE_CREDITS_BY_ID_FAILED = 'GET_MOVIE_CREDITS_BY_ID_FAILED'
export const CHANGE_MOVIE_CREDITS_PROPS = 'CHANGE_MOVIE_CREDITS_PROPS'

// TABS
export const CHANGE_TABS_MULTI_PROPS = 'CHANGE_TABS_MULTI_PROPS'

//INTERNET CONNECTION
export const CHECK_INTERNET_CONNECTION_STATUS = 'CHECK_INTERNET_CONNECTION_STATUS'
export const CHANGE_CONNECTION_PROP = 'CHANGE_CONNECTION_PROP'